In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)

In [15]:
df = pd.read_csv('../data/fraudTrain.csv')

In [16]:
df.head()

   Unnamed: 0 trans_date_trans_time            cc_num                            merchant       category     amt      first     last gender                        street            city state    zip      lat      long  city_pop                                job         dob                         trans_num   unix_time  merch_lat  merch_long  is_fraud
0           0   2019-01-01 00:00:18  2703186189652095          fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer    Banks      F                561 Perry Cove  Moravian Falls    NC  28654  36.0788  -81.1781      3495          Psychologist, counselling  1988-03-09  0b242abb623afc578575680df30655b9  1325376018  36.011293  -82.048315         0
1           1   2019-01-01 00:00:44      630423337322     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie     Gill      F  43039 Riley Greens Suite 393          Orient    WA  99160  48.8878 -118.2105       149  Special educational needs teacher  1978-06-21  1f76529f8574734946361c461b024d99  1325376044  49.159047 -118.186462         0
2           2   2019-01-01 00:00:51    38859492057661                fraud_Lind-Buckridge  entertainment  220.11     Edward  Sanchez      M      594 White Dale Suite 530      Malad City    ID  83252  42.1808 -112.2620      4154        Nature conservation officer  1962-01-19  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704 -112.154481         0
3           3   2019-01-01 00:01:16  3534093764340240  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00     Jeremy    White      M   9443 Cynthia Court Apt. 038         Boulder    MT  59632  46.2306 -112.1138      1939                    Patent attorney  1967-01-12  6b849c168bdad6f867558c3793159a81  1325376076  47.034331 -112.561071         0
4           4   2019-01-01 00:03:06   375534208663984                 fraud_Keeling-Crist       misc_pos   41.96      Tyler   Garcia      M              408 Bradley Rest        Doe Hill    VA  24433  38.4207  -79.4629        99     Dance movement psychotherapist  1986-03-28  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999  -78.632459         0

In [17]:
df.tail()

         Unnamed: 0 trans_date_trans_time               cc_num                             merchant       category     amt        first       last gender                         street                      city state    zip      lat      long  city_pop                               job         dob                         trans_num   unix_time  merch_lat  merch_long  is_fraud
1296670     1296670   2020-06-21 12:12:08       30263540414123                    fraud_Reichel Inc  entertainment   15.56         Erik  Patterson      M       162 Jessica Row Apt. 072                     Hatch    UT  84735  37.7175 -112.4777       258                      Geoscientist  1961-11-24  440b587732da4dc1a6395aba5fb41669  1371816728  36.841266 -111.690765         0
1296671     1296671   2020-06-21 12:12:19     6011149206456997             fraud_Abernathy and Sons    food_dining   51.70      Jeffrey      White      M  8617 Holmes Terrace Suite 651                 Tuscarora    MD  21790  39.2667  -77.5101       100  Production assistant, television  1979-12-11  278000d2e0d2277d1de2f890067dcc0a  1371816739  38.906881  -78.246528         0
1296672     1296672   2020-06-21 12:12:32     3514865930894695                 fraud_Stiedemann Ltd    food_dining  105.93  Christopher  Castaneda      M     1632 Cohen Drive Suite 639  High Rolls Mountain Park    NM  88325  32.9396 -105.8189       899                   Naval architect  1967-08-30  483f52fe67fabef353d552c1e662974c  1371816752  33.619513 -105.130529         0
1296673     1296673   2020-06-21 12:13:36     2720012583106919  fraud_Reinger, Weissnat and Strosin    food_dining   74.90       Joseph     Murray      M           42933 Ryan Underpass                 Manderson    SD  57756  43.3526 -102.5411      1126             Volunteer coordinator  1980-08-18  d667cdcbadaaed3da3f4020e83591c83  1371816816  42.788940 -103.241160         0
1296674     1296674   2020-06-21 12:13:37  4292902571056973207  fraud_Langosh, Wintheiser and Hyatt    food_dining    4.30      Jeffrey      Smith      M           135 Joseph Mountains                      Sula    MT  59871  45.8433 -113.8748       218          Therapist, horticultural  1995-08-16  8f7c8e4ab7f25875d753b422917c98c9  1371816817  46.565983 -114.186110         0

In [18]:
df.sample(10, random_state=42)

         Unnamed: 0 trans_date_trans_time               cc_num                                     merchant        category     amt    first        last gender                         street           city state    zip      lat      long  city_pop                                    job         dob                         trans_num   unix_time  merch_lat  merch_long  is_fraud
1045211     1045211   2020-03-09 15:09:26         577588686219                              fraud_Towne LLC        misc_pos  194.51    James  Strickland      M             25454 Leonard Lake  Spring Church    PA  15686  40.6153  -79.4545       972     Public relations account executive  1997-10-23  fff87d4340ef756a592eac652493cf6b  1362841766  40.420453  -78.865012         0
547406       547406   2019-08-22 15:49:01       30376238035123                            fraud_Friesen Ltd  health_fitness   52.32  Cynthia       Davis      F             7177 Steven Forges          Sixes    OR  97476  42.8250 -124.4409       217                    Retail merchandiser  1928-10-01  d0ad335af432f35578eea01d639b3621  1345650541  42.758860 -123.636337         0
110142       110142   2019-03-04 01:34:16     4658490815480264                               fraud_Mohr Inc    shopping_pos    6.53     Tara    Richards      F          4879 Cristina Station   Keisterville    PA  15449  39.9636  -79.7853       184                      Systems developer  1945-11-04  87f26e3ea33f4ff4c7a8bad2c7f48686  1330824856  40.475159  -78.898190         0
1285953     1285953   2020-06-16 20:04:38     3514897282719543                      fraud_Gaylord-Powlowski            home    7.33   Steven    Faulkner      M   841 Cheryl Centers Suite 115     Farmington    NY  14425  42.9580  -77.3083     10717                         Cytogeneticist  1952-10-13  9c34015321c0fa2ae6fd20f9359d1d3e  1371413078  43.767506  -76.542384         0
271705       271705   2019-05-14 05:54:48     6011381817520024  fraud_Christiansen, Goyette and Schamberger   gas_transport   64.29  Kristen       Allen      F      8619 Lisa Manors Apt. 871       Lagrange    WY  82221  41.6423 -104.1974       635  Product/process development scientist  1973-07-13  198437c05676f485e9be04449c664475  1336974888  41.040392 -104.092324         0
391181       391181   2019-06-28 10:46:05  4855488158131690372              fraud_Schuppe, Nolan and Hoeger    shopping_pos  129.80   Jeremy    Roberson      M             25887 Martin Inlet   Graniteville    VT   5654  44.1554  -72.4847       970                Agricultural consultant  1993-09-29  2203dd06764180b6314dca2b21df2494  1340880365  44.272392  -72.743707         0
962652       962652   2020-01-23 09:09:59       30427035050508                              fraud_Kuhic Inc     grocery_pos  111.10     John    Chandler      M  88325 Brandon Greens Apt. 477        Detroit    MI  48202  42.3770  -83.0796    673342                    Broadcast presenter  1969-11-20  7b44d808a40f8ac414736be6a038e83c  1358932199  42.170491  -83.291412         0
974821       974821   2020-01-30 11:23:44      213120463918358          fraud_Douglas, Schneider and Turner    shopping_pos    8.43   Willie      Jordan      M                   529 West Key    Spearsville    LA  71277  32.9550  -92.5870      1758                 Psychologist, forensic  1957-08-08  c5b880abe58cd5eedbda555cdb302d86  1359545024  32.019064  -91.779016         0
127056       127056   2019-03-11 10:35:53     6597888193422452                           fraud_Hickle Group    shopping_pos    2.36     Bill        Lane      M      4725 Hurst Curve Apt. 634       Holliday    TX  76366  33.6751  -98.6576      2317               Chief Technology Officer  1964-08-23  91376d8059070c4c481a6b47e763b195  1331462153  32.913817  -99.093146         0
1122630     1122630   2020-04-12 18:50:07        4809701904914                      fraud_Bahringer-Streich     food_dining   88.00  Sabrina       Nolan      F   312 Eric Expressway Apt. 014    Phenix City    AL  36869  32.4204  -85.0796     59744                      Chemical engineer  1984-02-07  f8a5ece3bf61877d1cab6dde1ec687ce  1365792607  32.167677  -85.957662         0

In [19]:
df.shape

(1296675, 23)

In [20]:
list(df.columns)

['Unnamed: 0',
 'trans_date_trans_time',
 'cc_num',
 'merchant',
 'category',
 'amt',
 'first',
 'last',
 'gender',
 'street',
 'city',
 'state',
 'zip',
 'lat',
 'long',
 'city_pop',
 'job',
 'dob',
 'trans_num',
 'unix_time',
 'merch_lat',
 'merch_long',
 'is_fraud']

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [25]:
df.describe()

         Unnamed: 0        cc_num           amt           zip           lat          long      city_pop     unix_time     merch_lat    merch_long      is_fraud
count  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06  1.296675e+06
mean   6.483370e+05  4.171920e+17  7.035104e+01  4.880067e+04  3.853762e+01 -9.022634e+01  8.882444e+04  1.349244e+09  3.853734e+01 -9.022646e+01  5.788652e-03
std    3.743180e+05  1.308806e+18  1.603160e+02  2.689322e+04  5.075808e+00  1.375908e+01  3.019564e+05  1.284128e+07  5.109788e+00  1.377109e+01  7.586269e-02
min    0.000000e+00  6.041621e+10  1.000000e+00  1.257000e+03  2.002710e+01 -1.656723e+02  2.300000e+01  1.325376e+09  1.902779e+01 -1.666712e+02  0.000000e+00
25%    3.241685e+05  1.800429e+14  9.650000e+00  2.623700e+04  3.462050e+01 -9.679800e+01  7.430000e+02  1.338751e+09  3.473357e+01 -9.689728e+01  0.000000e+00
50%    6.483370e+05  3.521417e+15  4.752000e+01  4.817400e+04  3.935430e+01 -8.747690e+01  2.456000e+03  1.349250e+09  3.936568e+01 -8.743839e+01  0.000000e+00
75%    9.725055e+05  4.642255e+15  8.314000e+01  7.204200e+04  4.194040e+01 -8.015800e+01  2.032800e+04  1.359385e+09  4.195716e+01 -8.023680e+01  0.000000e+00
max    1.296674e+06  4.992346e+18  2.894890e+04  9.978300e+04  6.669330e+01 -6.795030e+01  2.906700e+06  1.371817e+09  6.751027e+01 -6.695090e+01  1.000000e+00

In [24]:
df.describe(include='object')

       trans_date_trans_time           merchant       category        first     last   gender               street        city    state                job         dob                         trans_num
count                1296675            1296675        1296675      1296675  1296675  1296675              1296675     1296675  1296675            1296675     1296675                           1296675
unique               1274791                693             14          352      481        2                  983         894       51                494         968                           1296675
top      2019-04-22 16:02:01  fraud_Kilback LLC  gas_transport  Christopher    Smith        F  864 Reynolds Plains  Birmingham       TX  Film/video editor  1977-03-23  0b242abb623afc578575680df30655b9
freq                       4               4403         131659        26669    28794   709863                 3123        5617    94876               9779        5636                                 1

In [26]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [78]:
df.trans_num.duplicated().sum()

np.int64(0)

In [28]:
df.dtypes

Unnamed: 0                 int64
trans_date_trans_time     object
cc_num                     int64
merchant                  object
category                  object
amt                      float64
first                     object
last                      object
gender                    object
street                    object
city                      object
state                     object
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                       object
dob                       object
trans_num                 object
unix_time                  int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

In [37]:
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time']) 
df['dob'] = pd.to_datetime(df['dob'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  datetime64[ns]
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  datetime64[ns]
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: datetime64[ns](2), float64(5), int64(6), object(10)
memory usage: 227.5+ MB

In [39]:
df['trans_date_trans_time'].agg(['min', 'max'])

min   2019-01-01 00:00:18
max   2020-06-21 12:13:37
Name: trans_date_trans_time, dtype: datetime64[ns]

In [40]:
df['dob'].agg(['min', 'max'])

min   1924-10-30
max   2005-01-29
Name: dob, dtype: datetime64[ns]

In [57]:
# Total minor customers (Age below 18 years old) in the dataset
df[(df['dob'] < '2005-01-29') & (df['dob'] > '2001-01-01')].cc_num.nunique()

12

In [69]:
df['is_fraud'].value_counts(normalize=True)*100

is_fraud
0    99.421135
1     0.578865
Name: proportion, dtype: float64

In [56]:
df.nunique()

Unnamed: 0               1296675
trans_date_trans_time    1274791
cc_num                       983
merchant                     693
category                      14
amt                        52928
first                        352
last                         481
gender                         2
street                       983
city                         894
state                         51
zip                          970
lat                          968
long                         969
city_pop                     879
job                          494
dob                          968
trans_num                1296675
unix_time                1274823
merch_lat                1247805
merch_long               1275745
is_fraud                       2
dtype: int64

In [53]:
df.select_dtypes(include=np.number).columns

Index(['Unnamed: 0', 'cc_num', 'amt', 'zip', 'lat', 'long', 'city_pop', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud'], dtype='object')

In [54]:
df.select_dtypes(include=object).columns

Index(['merchant', 'category', 'first', 'last', 'gender', 'street', 'city', 'state', 'job', 'trans_num'], dtype='object')

In [66]:
df.category.unique()

array(['misc_net', 'grocery_pos', 'entertainment', 'gas_transport',
       'misc_pos', 'grocery_net', 'shopping_net', 'shopping_pos',
       'food_dining', 'personal_care', 'health_fitness', 'travel',
       'kids_pets', 'home'], dtype=object)

In [67]:
df.state.unique()

array(['NC', 'WA', 'ID', 'MT', 'VA', 'PA', 'KS', 'TN', 'IA', 'WV', 'FL',
       'CA', 'NM', 'NJ', 'OK', 'IN', 'MA', 'TX', 'WI', 'MI', 'WY', 'HI',
       'NE', 'OR', 'LA', 'DC', 'KY', 'NY', 'MS', 'UT', 'AL', 'AR', 'MD',
       'GA', 'ME', 'AZ', 'MN', 'OH', 'CO', 'VT', 'MO', 'SC', 'NV', 'IL',
       'NH', 'SD', 'AK', 'ND', 'CT', 'RI', 'DE'], dtype=object)

In [68]:
df.city.unique()

array(['Moravian Falls', 'Orient', 'Malad City', 'Boulder', 'Doe Hill',
       'Dublin', 'Holcomb', 'Edinburg', 'Manor', 'Clarksville',
       'Clarinda', 'Shenandoah Junction', 'Saint Petersburg', 'Grenada',
       'High Rolls Mountain Park', 'Harrington Park', 'Lahoma',
       'Carlisle', 'Harborcreek', 'Elizabeth', 'Methuen', 'Moulton',
       'Plainfield', 'May', 'Waukesha', 'Bailey', 'Romulus', 'Freedom',
       'Honokaa', 'Valentine', 'Westfir', 'Tiptonville', 'Republic',
       'Baton Rouge', 'Washington', 'Big Creek', 'Bellmore', 'Florence',
       'Allentown', 'Moriches', 'Esbon', 'Chatham', 'Thompson',
       'North Prairie', 'Laredo', 'Grant', 'Conway', 'New Goshen',
       'Sunflower', 'Enola', 'Roosevelt', 'Pointe Aux Pins', 'Dallas',
       'Jay', 'North Tonawanda', 'Athena', 'Chester', 'Elkhart',
       'Surrency', 'Arcadia', 'Gaithersburg', 'Bowdoin', 'Heart Butte',
       'San Jose', 'Rumely', 'Cranks', 'Ravenna', 'Utica', 'Uledi',
       'Naples', 'Thida', 'Parks', 'Central', 'Fort Washakie', 'Etlan',
       'Brinson', 'Shrewsbury', 'Bigelow', 'North Washington', 'Holloway',
       'Littleton', 'Hinesburg', 'Meadville', 'Elberta', 'Moab',
       'Diamond', 'Bradley', 'Hopewell', 'Hawthorne', 'Kensington',
       'Ruth', 'Avoca', 'Princeton', 'Sherman', 'Loxahatchee',
       'Smackover', 'Cokeburg', 'Leetsdale', 'Manville',
       'Westhampton Beach', 'New York City', 'Halstad', 'Allenhurst',
       'June Lake', 'Sixes', 'Holstein', 'Brantley', 'Paxton',
       'Westerville', 'Timberville', 'Dunlevy', 'Coyle', 'Elizabethtown',
       'Garrattsville', 'Lomax', 'Egan', 'Brownville', 'Drakes Branch',
       'Ballwin', 'Fields Landing', 'West Palm Beach', 'West Chazy',
       'Lebanon', 'Jones', 'Burke', 'Webster City', 'Ozawkie',
       'Blackville', 'Damascus', 'Sea Island', 'Rule', 'Jefferson',
       'Huntsville', 'Hinckley', 'Acworth', 'Camden', 'Smiths Grove',
       'Philadelphia', 'Murrayville', 'Melbourne', 'Palmyra', 'Jermyn',
       'Belfast', 'West Sayville', 'Sturgis', 'Lohrville', 'Arlington',
       'Saint Paul', 'Girard', 'Fairview', 'Farmington', 'Kilgore',
       'Springfield', 'Lepanto', 'Karnack', 'Louisiana', 'Kansas City',
       'Mesa', 'Pomona', 'Lonetree', 'Port Saint Lucie', 'Centerview',
       'Colorado Springs', 'Easton', 'West Columbia', 'Maysville',
       'Muskegon', 'Johns Island', 'Metairie', 'Blairsden-Graeagle',
       'Hampton', 'Viola', 'Paulding', 'Sontag', 'Clutier', 'Reno',
       'Barnstable', 'Cardwell', 'Kingsford Heights', 'Phoenix',
       'Newhall', 'Norwalk', 'Mc Nabb', 'Tulsa', 'Barnard', 'San Antonio',
       'Bridger', 'Tomales', 'Mallie', 'Oxford', 'Turner', 'Eureka',
       'Marietta', 'Redford', 'Weeping Water', 'Waynesfield', 'Portland',
       'Greenwood', 'Boonton', 'Murfreesboro', 'Warren', 'Meridian',
       'Cherokee Village', 'Bristow', 'Ash Flat', 'Iliff', 'Deadwood',
       'Burlington', 'Wales', 'Churubusco', 'Afton', 'Cochranton',
       'Mound City', 'West Harrison', 'Pembroke Township', 'Joliet',
       'Fulton', 'Saint Bonaventure', 'Keisterville', 'Greenview',
       'Lakeport', 'Rock Tavern', 'Llano', 'Altair', 'Harrodsburg',
       'Carlotta', 'Wittenberg', 'Des Moines', 'Auburn', 'Dadeville',
       'Wilton', 'Ollie', 'Mifflin', 'Amsterdam', 'Manderson', 'Holliday',
       'Dumont', 'Payson', 'Birmingham', 'Creola', 'Texarkana',
       'Fullerton', 'Ruckersville', 'Blooming Grove', 'Comfort',
       'Louisville', 'Atglen', 'North Loup', 'Grassflat', 'Mill Creek',
       'Moores Hill', 'Browning', 'Smithfield', 'Cromona', 'Kent',
       'Harwood', 'Delhi', 'Gadsden', 'Brooklin', 'Bay Minette',
       'Higganum', 'Ashfield', 'Fiddletown', 'Andrews',
       'Huntington Beach', 'Westport', 'Comfrey', 'Heidelberg', 'Powell',
       'De Witt', 'Howes Cave', 'Oolitic', 'Belmond', 'Mooresville',
       'Steuben', 'Armagh', 'Edisto Island', 'Marathon', 'Port Gibson',
       'Brandon', 'Tallmansville', 'Glendale', 'El Paso', 'Lamberton',
       'Manchester', 'Emporium', 'Alva', 'Roma', 'Prairie Hill',
       'Blairstown', 'Bridgeport', 'Grand Junction', 'Tamaroa',
       'Great Mills', 'Laguna Hills', 'West Decatur', 'Aledo', 'Pelham',
       'Albuquerque', 'Scotland', 'Azusa', 'Lanark Village',
       'Cuyahoga Falls', 'Manistique', 'Mountain Park', 'University',
       'Breesport', 'Harper', 'Bagley', 'Fenelton', 'Gardiner',
       'Greendale', 'Bay City', 'Minneapolis', 'Gregory', 'Tuscarora',
       'Northport', 'Rock Springs', 'Altona', 'Paauilo', 'Ratcliff',
       'Mount Morris', 'Pembroke', 'Pittsburgh', 'West Henrietta',
       'Tickfaw', 'Rhame', 'Eugene', 'Seneca', 'Daly City', 'Logan',
       'Coleman', 'Norman', 'Cape Coral', 'Summerfield', 'Daniels',
       'Tampa', 'Gainesville', 'East Canaan', 'Dresden', 'Luzerne',
       'Parkers Lake', 'Olmsted', 'Mendon', 'Fayetteville', 'Notrees',
       'Pecos', 'Brunson', 'Belgrade', 'Kenner', 'Stillwater', 'Cadiz',
       'Avera', 'Annapolis', 'Powell Butte', 'Rosewood', 'Lima', 'Thrall',
       'Union', 'Riverview', 'Hannawa Falls', 'Cazenovia', 'North Judson',
       'Fordoche', 'Bauxite', 'Cisco', 'Apison', 'Cass', 'Santa Monica',
       'Amorita', 'Laramie', 'Hudson', 'Center Point', 'Lagrange',
       'Dexter', 'Brainard', 'Winger', 'Thomas', 'Shelter Island',
       'Tupper Lake', 'Humboldt', 'Winter', 'Corona', 'Lakeland',
       'Vienna', 'Goreville', 'Yellowstone National Park', 'Shedd',
       'Wilmington', 'Mc Cracken', 'Milner', 'Noonan', 'Falconer',
       'Desdemona', 'Bethel Springs', 'Burns Flat', 'Glen Rock', 'Basye',
       'Lowville', 'Du Pont', 'Burrton', 'Lubbock', 'Independence',
       'Creedmoor', 'Wichita', 'Houston', 'Clay Center', 'Sebring',
       'Whittemore', 'Ogdensburg', 'Spearsville', 'Oaks',
       'Paradise Valley', 'Burbank', 'New Holstein', 'Schaefferstown',
       'Washington Court House', 'Eldridge', 'San Diego', 'Marienville',
       'Fort Myers', 'Kissee Mills', 'Bronx', 'Montandon', 'Espanola',
       'Campbell', 'Indian Wells', 'Hewitt', 'Leo', 'Mulberry Grove',
       'Mountain Center', 'Helm', 'Detroit', 'Moundsville', 'Falmouth',
       'Zaleski', 'Lowell', 'Henderson', 'Corsica', 'Wilmette',
       'Mayersville', 'Pearlington', 'Cleveland', 'Whigham', 'Kirby',
       'Knoxville', 'Highland', 'Hazel', 'Alexandria', 'Port Ewen',
       'Lamy', 'Mount Clemens', 'North Wilkesboro', 'Morrisdale', 'Cord',
       'Sauk Rapids', 'Center Tuftonboro', 'Hatch', 'Margaretville',
       'Goodrich', 'Ford', 'South Londonderry', 'Cross Plains',
       'Lake Jackson', 'Orangeburg', 'Walnut Ridge', 'Tower Hill',
       'Oakland', 'Montrose', 'Parker Dam', 'Rocky Mount', 'Coleharbor',
       'Falls City', 'Moriarty', 'Southfield', 'Glade Spring', 'Slayden',
       'O Brien', 'Bristol', 'Umatilla', 'Hooper', 'Saint Amant',
       'Clayton', 'Cascade Locks', 'Saint James City', 'Vinton',
       'Christine', 'Alder', 'Roseland', 'Tyaskin', 'Lake Oswego',
       'Parker', 'Wauchula', 'Colton', 'Juliette', 'River',
       'Beaver Falls', 'Elk Rapids', 'Lonsdale', 'West Hartford',
       'Kirtland Afb', 'Shields', 'Riverton', 'Whaleyville', 'Sacramento',
       'Marion', 'Adams', 'Zavalla', 'Cottekill', 'Shippingport',
       'Montgomery', 'Sun City', 'Grover', 'Newport',
       'South Richmond Hill', 'Parsonsfield', 'Garfield', 'Jelm',
       'Meredith', 'Battle Creek', 'Woodville', 'Luray', 'Cowlesville',
       'Haw River', 'Falls Church', 'Topeka', 'Haynes', 'Grimesland',
       'Smith River', 'Moorhead', 'White Sulphur Springs', 'East Andover',
       'Superior', 'Hurricane', 'Bowersville', 'Mount Saint Joseph',
       'Hancock', 'Dubre', 'Collettsville', 'Rossville', 'Red River',
       'Benton', 'Monmouth Beach', 'Bessemer', 'Greenbush', 'Reynolds',
       'Nazareth', 'Hovland', 'Alpharetta', 'Canton', 'Catawba',
       'Scarborough', 'Hopkins', 'Norman Park', 'Sachse', 'Arvada',
       'Winthrop', 'De Soto', 'Sutherland', 'Grandview', 'Manquin',
       'Owensville', 'Altonah', 'Titusville', 'Paris', 'Humble', 'Mounds',
       'Lolita', 'Wetmore', 'Keller', 'Amanda', 'Scotia', 'Pueblo',
       'Purmela', 'Chester Heights', 'Clarks Mills', 'Mount Hope',
       'West Eaton', 'Beaverdam', 'Randolph', 'Greenwich', 'Ragland',
       'Phenix City', 'Coffeeville', 'Stirling', 'Issaquah',
       'Old Hickory', 'West Long Branch', 'Ronceverte', 'Sula',
       'Belle Fourche', 'Vero Beach', 'Curlew', 'Tyler', 'Miamisburg',
       'Providence', 'Saint Louis', 'Duncan', 'De Lancey', 'Lawn',
       'Tryon', 'Milwaukee', 'New Ellenton', 'East Troy', 'Saxon',
       'West Green', 'Atlantic', 'Mc Veytown', 'Ferney', 'Corriganville',
       'Pikesville', 'Cecilton', 'Wheaton', 'Palmdale', 'New Memphis',
       'Newton', 'Valdosta', 'Jordan Valley', 'Edmond', 'Hills',
       'Waupaca', 'Darien', 'Milford', 'De Queen', 'Newberg', 'Plymouth',
       'Columbia', 'Belmont', 'Quanah', 'Barneveld', 'Newark Valley',
       'Downsville', 'American Fork', 'Clifton', 'Stayton', 'Bonfield',
       'Napa', 'West Monroe', 'Dayton', 'Hawley', 'Kingsport', 'Moro',
       'Livonia', 'Sheffield', 'Gretna', 'Haines City', 'Key West',
       'Stanchfield', 'Rockwood', 'Hahira', 'Munith', 'Minnesota Lake',
       'New Waverly', 'Sprague', 'Dieterich', 'Mansfield', 'Winfield',
       'Rochester', 'Oran', 'Orr', 'Crownpoint', 'Putnam', 'San Angelo',
       'Eagarville', 'Leonard', 'Claremont', 'Spencer', 'Nelson',
       'Rockwell', 'Ringwood', 'Oakdale', 'Nokomis', 'Bethel', 'Cedar',
       'Loami', 'Spring Church', 'Brashear', 'Tekoa', 'Kingsville',
       'Galatia', 'Dell City', 'Emmons', 'Norwich', 'Maria Stein',
       'Georgetown', 'Clearwater', 'Albany', 'Indianapolis', 'Red Cliff',
       'Omaha', 'Brooklyn', 'Richland', 'Arnold', 'Odessa', 'Iselin',
       'Washoe Valley', 'Denham Springs', 'Mobile', 'Vanderbilt',
       'Varnell', 'Halma', 'Oriskany Falls', 'Ranier', 'Lawrence',
       'Hurley', 'Grand Bay', 'Sardis', 'Woods Cross', 'Broomfield',
       'Schaumburg', 'Saint Francis', 'Heiskell', 'Unionville',
       'Nobleboro', 'South Hero', 'Carroll', 'Achille', 'Lithopolis',
       'Manley', 'Graniteville', 'Plantersville', 'Jaffrey',
       'Liberty Mills', 'Stephensport', 'Matawan', 'Grantham', 'Tomahawk',
       'Lakeview', 'Lane', 'Pewee Valley', 'Bolton', 'Matthews',
       'Jordanville', 'Syracuse', 'Ruidoso', 'Oak Hill', 'Cressona',
       'Early', 'Bryant', 'Bynum', 'Palermo', 'Fairhope', 'Remer',
       'Baroda', 'Howells', 'Beasley', 'Phil Campbell', 'Deane',
       'North Haverhill', 'Mount Perry', 'Prairie Creek', 'Grand Ridge',
       'Oklahoma City', 'Ashford', 'Huslia', 'Irvine', 'Ehrhardt',
       'Prosperity', 'Dongola', 'Paint Rock', 'Dalton', 'Smock',
       'Bolivar', 'Spring', 'Ridgeland', 'West Finley', 'Lorenzo',
       'Clune', 'Port Costa', 'Oconto Falls', 'Preston', 'Bonita Springs',
       'Hartford', 'Hedrick', 'Boyd', 'Big Indian', 'Cuthbert',
       'Sterling City', 'Queenstown', 'Trenton', 'Kirk', 'Gibsonville',
       'North Brookfield', 'Akron', 'Monitor', 'New Boston', 'Monetta',
       'Mc Intosh', 'Watertown', 'Alton', 'Rock Glen', 'East Rochester',
       'Armonk', 'Stoneham', 'Winslow', 'Williamsburg', 'Mc Clellandtown',
       'Hedley', 'Skytop', 'Cross', 'Deltona', 'Irwinton',
       'North Augusta', 'Collegeville', 'Knowlesville', 'Oakford',
       'Aurora', 'Heislerville', 'Scotts Mills', 'Moscow', 'Williams',
       'Premier', 'Port Charlotte', 'Wendel', 'Harmony',
       'Springfield Gardens', 'North Las Vegas', 'Port Richey',
       'Linthicum Heights', 'Veedersburg', 'Loving', 'Stittville',
       'Kittery Point', 'Greenville', 'Los Angeles', 'Ironton',
       'Vancouver', 'Jackson', 'Kings Bay', 'Thornville', 'Cassatt',
       'Michigan', 'Spirit Lake', 'Pea Ridge', 'West Bethel',
       'New Franken', 'Waukau', 'Crouse', 'Vacaville', 'Madisonville',
       'La Grande', 'Greenport', 'West Frankfort', 'Chattanooga',
       'Gaines', 'Phelps', 'Hubbell', 'Mount Vernon', 'Beacon', 'Clinton',
       'Claypool', 'Walkertown', 'Kaktovik', 'Coulee Dam',
       'Mountain City', 'Granbury', 'Ashland', 'Clarion', 'Downey',
       'Morven', 'Medford', 'Melville', 'Ridge Spring', 'Mineral',
       'Orange Park', 'Norfolk', 'Irvington', 'Oakton', 'Wappapello',
       'Nanuet', 'Seattle', 'Pleasant Hill', 'Karns City', 'North East',
       'Byesville', 'Roland', 'Marshall', 'Isanti', 'Winnsboro',
       'Noblesville', 'Las Vegas', 'Bruce', 'Buellton', 'Grenola',
       'Streator', 'Wartburg', 'East China', 'Brookfield', 'Angwin',
       'Nicholson', 'Lockhart', 'Moss Point', 'Queen Anne', 'Freeport'],
      dtype=object)

In [ ]:
df.merchant.unique()

array(['fraud_Rippin, Kub and Mann', 'fraud_Heller, Gutmann and Zieme',
       'fraud_Lind-Buckridge', 'fraud_Kutch, Hermiston and Farrell',
       'fraud_Keeling-Crist', 'fraud_Stroman, Hudson and Erdman',
       'fraud_Rowe-Vandervort', 'fraud_Corwin-Collins',
       'fraud_Herzog Ltd', 'fraud_Schoen, Kuphal and Nitzsche',
       'fraud_Rutherford-Mertz', 'fraud_Kerluke-Abshire',
       'fraud_Lockman Ltd', 'fraud_Kiehn Inc', 'fraud_Beier-Hyatt',
       'fraud_Schmidt and Sons', 'fraud_Lebsack and Sons',
       'fraud_Mayert Group', 'fraud_Konopelski, Schneider and Hartmann',
       'fraud_Schultz, Simonis and Little', 'fraud_Bauch-Raynor',
       'fraud_Harris Inc', 'fraud_Kling-Grant', 'fraud_Pacocha-Bauch',
       'fraud_Lesch Ltd', 'fraud_Kunde-Sanford', "fraud_Deckow-O'Conner",
       'fraud_Bruen-Yost', 'fraud_Kunze Inc',
       'fraud_Nitzsche, Kessler and Wolff',
       'fraud_Kihn, Abernathy and Douglas', 'fraud_Torphy-Goyette',
       'fraud_Balistreri-Nader', 'fraud_Bahringer, Schoen and Corkery',
       'fraud_Hudson-Ratke', 'fraud_Heidenreich PLC',
       'fraud_Halvorson Group', 'fraud_Harber Inc',
       'fraud_Mosciski, Gislason and Mertz',
       'fraud_Christiansen, Goyette and Schamberger', 'fraud_Howe Ltd',
       'fraud_Ledner-Pfannerstill', 'fraud_Koepp-Witting',
       'fraud_Doyle Ltd', 'fraud_Schaefer, Maggio and Daugherty',
       'fraud_Stracke-Lemke', 'fraud_Mosciski, Ziemann and Farrell',
       'fraud_Cartwright-Harris', "fraud_Pacocha-O'Reilly",
       'fraud_Pfeffer LLC', 'fraud_Huels-Hahn', 'fraud_Volkman PLC',
       'fraud_Kiehn-Emmerich', 'fraud_Kemmer-Buckridge',
       'fraud_Cummerata-Jones', 'fraud_Goldner, Kovacek and Abbott',
       'fraud_Spinka-Welch', 'fraud_Huel-Langworth',
       'fraud_Macejkovic-Lesch', 'fraud_Morar Inc',
       'fraud_Eichmann, Bogan and Rodriguez',
       'fraud_Huel, Hammes and Witting', 'fraud_Ferry, Lynch and Kautzer',
       'fraud_Heathcote LLC', 'fraud_Little, Gutmann and Lynch',
       'fraud_Jaskolski-Dibbert', 'fraud_Hackett-Lueilwitz',
       'fraud_Cummings LLC', 'fraud_Swaniawski, Lowe and Robel',
       'fraud_Osinski, Ledner and Leuschke',
       'fraud_Reichert, Huels and Hoppe', 'fraud_Ankunding LLC',
       'fraud_Pfeffer and Sons', 'fraud_Greenholt, Jacobi and Gleason',
       'fraud_Connelly, Reichert and Fritsch', 'fraud_Torp-Labadie',
       'fraud_Wolf Inc', 'fraud_VonRueden Group', 'fraud_Vandervort-Funk',
       'fraud_Bernhard Inc', 'fraud_Morissette, Weber and Wiegand',
       'fraud_Brekke and Sons', 'fraud_Mraz-Herzog',
       'fraud_Padberg-Welch', 'fraud_Kutch-Hegmann',
       'fraud_Corwin-Gorczany', 'fraud_Huels-Nolan', 'fraud_DuBuque LLC',
       'fraud_Schmeler Inc', 'fraud_Schaefer, McGlynn and Bosco',
       'fraud_Williamson LLC', 'fraud_Pouros-Conroy',
       'fraud_Erdman-Kertzmann', 'fraud_Kuhn LLC',
       'fraud_Fisher-Schowalter', 'fraud_Medhurst PLC',
       'fraud_Kerluke Inc', 'fraud_Stark-Batz',
       'fraud_Gottlieb, Considine and Schultz',
       'fraud_Adams, Kovacek and Kuhlman', 'fraud_Grimes LLC',
       'fraud_Rodriguez Group', 'fraud_Wuckert-Walter',
       'fraud_Weber and Sons', 'fraud_Herman, Treutel and Dickens',
       'fraud_Rau and Sons', 'fraud_Koss and Sons',
       'fraud_Smitham-Schiller', 'fraud_Hills-Olson', 'fraud_Durgan-Auer',
       'fraud_McDermott-Rice', 'fraud_Raynor, Reinger and Hagenes',
       'fraud_Powlowski-Weimann', 'fraud_Langosh, Wintheiser and Hyatt',
       'fraud_Baumbach, Hodkiewicz and Walsh', 'fraud_Rempel Inc',
       'fraud_Bins-Rice', 'fraud_Emard Inc', 'fraud_Kutch and Sons',
       'fraud_Fisher Inc', 'fraud_Olson, Becker and Koch',
       "fraud_Friesen-D'Amore", 'fraud_Reilly, Heaney and Cole',
       'fraud_Boyer PLC', 'fraud_Luettgen PLC', 'fraud_Cassin-Harvey',
       'fraud_Funk Group', 'fraud_Goodwin-Nitzsche',
       'fraud_Parisian, Schiller and Altenwerth', 'fraud_Metz-Boehm',
       'fraud_Monahan, Bogisich and Ledner', 'fraud_Koelpin and Sons',
       'fraud_Kuhic LLC', 'fraud_Koepp-Parker',
       'fraud_Stehr, Jewess and Schimmel',
       'fraud_Quitzon, Green and Bashirian',
       'fraud_Nicolas, Hills and McGlynn', 'fraud_Leannon-Ward',
       'fraud_Friesen-Stamm', 'fraud_Botsford Ltd', 'fraud_Bradtke PLC',
       'fraud_Zieme, Bode and Dooley', 'fraud_Hills-Witting',
       'fraud_Brown-Greenholt', 'fraud_Bernhard, Grant and Langworth',
       'fraud_Wiza, Schaden and Stark', 'fraud_Buckridge PLC',
       'fraud_Kilback LLC', 'fraud_Spinka Inc',
       'fraud_Kerluke, Kertzmann and Wiza',
       'fraud_Ferry, Reichel and DuBuque', 'fraud_Price Inc',
       'fraud_Johnston, Nikolaus and Maggio', 'fraud_Berge LLC',
       'fraud_Conroy-Cruickshank', 'fraud_Abshire PLC',
       'fraud_Gleason-Macejkovic', 'fraud_McGlynn-Jaskolski',
       'fraud_Bartoletti-Wunsch', 'fraud_Cole PLC',
       'fraud_Lehner, Reichert and Mills', 'fraud_McCullough LLC',
       'fraud_Schmitt Ltd', 'fraud_Pouros-Haag',
       'fraud_Strosin-Cruickshank', 'fraud_Weimann, Kuhic and Beahan',
       'fraud_Donnelly PLC', 'fraud_Lockman, West and Runte',
       'fraud_Torp-Lemke', 'fraud_Kris-Weimann',
       'fraud_Rodriguez, Yost and Jenkins', 'fraud_Wiegand-Lowe',
       'fraud_Auer-Mosciski', 'fraud_Okuneva, Schneider and Rau',
       'fraud_Kassulke PLC', 'fraud_Dach-Nader', 'fraud_Cummings Group',
       'fraud_Reichert, Shanahan and Hayes',
       'fraud_Tromp, Kerluke and Glover',
       'fraud_Bins, Balistreri and Beatty', 'fraud_Trantow PLC',
       'fraud_Miller-Hauck', 'fraud_Kuvalis Ltd', 'fraud_Dickinson Ltd',
       'fraud_Stanton, Jakubowski and Baumbach',
       'fraud_Rohan, White and Aufderhar',
       'fraud_Cormier, Stracke and Thiel',
       'fraud_Tillman, Fritsch and Schmitt',
       'fraud_Christiansen-Gusikowski',
       'fraud_Jenkins, Hauck and Friesen', 'fraud_Reichel Inc',
       'fraud_Prohaska-Murray', 'fraud_Parker, Nolan and Trantow',
       'fraud_Volkman Ltd', 'fraud_Streich, Hansen and Veum',
       'fraud_Kutch LLC', 'fraud_Barton Inc', 'fraud_Dooley-Thompson',
       'fraud_Flatley Group', 'fraud_Turcotte-Halvorson',
       'fraud_Lynch Ltd', 'fraud_Romaguera, Cruickshank and Greenholt',
       'fraud_Gutmann Ltd', 'fraud_Sporer Inc',
       'fraud_Runolfsson and Sons', 'fraud_Block Group',
       'fraud_Bahringer-Larson', 'fraud_Rowe, Batz and Goodwin',
       'fraud_Schmitt Inc', 'fraud_Maggio-Fahey',
       'fraud_Haley, Jewess and Bechtelar',
       'fraud_Ruecker, Beer and Collier',
       'fraud_Robel, Cummerata and Prosacco', 'fraud_Jast-McDermott',
       'fraud_Bernier, Volkman and Hoeger', 'fraud_Heaney-Marquardt',
       'fraud_Hudson-Grady', 'fraud_Towne, Walker and Borer',
       'fraud_Terry-Huel', 'fraud_Kihn-Fritsch', 'fraud_Eichmann-Russel',
       'fraud_Miller-Harris', 'fraud_Schumm PLC',
       'fraud_Greenfelder, Bartoletti and Davis',
       'fraud_Kovacek, Dibbert and Ondricka', 'fraud_Hermann-Gaylord',
       'fraud_Bailey-Morar', 'fraud_McDermott-Weimann', 'fraud_Welch Inc',
       'fraud_Auer-West', 'fraud_Boehm, Predovic and Reinger',
       'fraud_Dibbert and Sons', 'fraud_Lind, Huel and McClure',
       'fraud_Casper, Hand and Zulauf', 'fraud_McCullough Group',
       'fraud_Streich, Dietrich and Barton', "fraud_O'Keefe-Hudson",
       'fraud_Pagac LLC', 'fraud_Bernier, Streich and Jewess',
       "fraud_Greenholt, O'Hara and Balistreri", 'fraud_Dickinson-Rempel',
       'fraud_Dare-Marvin', 'fraud_Spencer PLC', 'fraud_Stamm-Rodriguez',
       'fraud_Langworth, Boehm and Gulgowski',
       'fraud_Larkin, Stracke and Greenfelder',
       'fraud_Yost, Block and Koepp',
       'fraud_Douglas, Schneider and Turner', 'fraud_Kuphal-Predovic',
       'fraud_Parisian and Sons', 'fraud_Flatley-Durgan',
       'fraud_Gislason Group', 'fraud_Bednar Group',
       'fraud_Heller-Langosh', 'fraud_Zboncak Ltd', 'fraud_Gerlach Inc',
       'fraud_Wilkinson Ltd', 'fraud_Moen, Reinger and Murphy',
       'fraud_Kerluke, Considine and Macejkovic', 'fraud_Upton PLC',
       'fraud_Bogisich Inc', 'fraud_Marks Inc', 'fraud_Murray-Smitham',
       'fraud_Frami Group', 'fraud_Ortiz Group', 'fraud_Goldner-Lemke',
       'fraud_Hickle Group', 'fraud_Conroy Ltd',
       'fraud_Schumm, Bauch and Ondricka', 'fraud_McGlynn-Heathcote',
       'fraud_Herman Inc', 'fraud_Gutmann-Upton',
       'fraud_Volkman-Predovic',
       'fraud_Wintheiser, Dietrich and Schimmel',
       'fraud_Raynor, Feest and Miller', 'fraud_Bogisich-Homenick',
       'fraud_Jast and Sons', 'fraud_Baumbach, Strosin and Nicolas',
       'fraud_Towne, Greenholt and Koepp', "fraud_Schamberger-O'Keefe",
       'fraud_Nienow PLC', 'fraud_Emmerich-Luettgen', 'fraud_Mante Group',
       'fraud_Baumbach, Feeney and Morar', 'fraud_Thiel PLC',
       'fraud_Mohr Inc', 'fraud_Hagenes, Kohler and Hoppe',
       'fraud_Block-Parisian', 'fraud_Dooley Inc',
       'fraud_Bashirian Group', 'fraud_Cremin, Hamill and Reichel',
       'fraud_Sawayn PLC', 'fraud_Jewess LLC', 'fraud_Roberts-Beahan',
       'fraud_Brown PLC', 'fraud_Tillman, Dickinson and Labadie',
       'fraud_Reichert, Rowe and Mraz', 'fraud_Kilback Group',
       'fraud_Spencer-Runolfsson', 'fraud_Labadie, Treutel and Bode',
       'fraud_Dach-Borer', 'fraud_Johnson, Runolfsdottir and Mayer',
       'fraud_Smitham-Boehm', 'fraud_Moore, Dibbert and Koepp',
       'fraud_Hamill-Daugherty', 'fraud_Watsica, Haag and Considine',
       'fraud_Smith-Stokes', 'fraud_Kuhic, Bins and Pfeffer',
       'fraud_Nader-Heller', 'fraud_Kozey-Boehm', 'fraud_Stiedemann Inc',
       'fraud_Lehner, Mosciski and King', 'fraud_Reynolds-Schinner',
       'fraud_Koss, McLaughlin and Mayer', 'fraud_Terry, Johns and Bins',
       'fraud_Kemmer-Reinger', 'fraud_Larson-Moen', 'fraud_Kuhic Inc',
       'fraud_Kris-Padberg', 'fraud_Schmeler, Bashirian and Price',
       'fraud_Klocko LLC', 'fraud_Schaefer, Fay and Hilll',
       'fraud_Kling Inc', 'fraud_Turner and Sons', 'fraud_Mohr-Bayer',
       'fraud_Wiza LLC', 'fraud_Skiles-Ankunding',
       'fraud_Jaskolski-Vandervort', 'fraud_Kerluke PLC',
       'fraud_Ernser-Lynch', 'fraud_Zboncak, Rowe and Murazik',
       'fraud_Stoltenberg-Beatty', 'fraud_Kuphal-Bartoletti',
       'fraud_Rempel PLC', 'fraud_Denesik and Sons', 'fraud_Goyette Inc',
       'fraud_Dicki Ltd', 'fraud_Stokes, Christiansen and Sipes',
       'fraud_Hermann and Sons', 'fraud_Gibson-Deckow',
       'fraud_Douglas-White', 'fraud_Murray Ltd', 'fraud_McKenzie-Huels',
       'fraud_Runte-Mohr', 'fraud_Roob, Conn and Tremblay',
       'fraud_Boyer-Reichert', 'fraud_Shanahan-Lehner',
       'fraud_Greenholt Ltd', 'fraud_Kulas Group',
       'fraud_Dare, Fritsch and Zboncak', 'fraud_Waters-Cruickshank',
       'fraud_Kunze, Larkin and Mayert', 'fraud_Bednar Inc',
       'fraud_Schimmel-Olson', 'fraud_Lubowitz, Terry and Stracke',
       'fraud_Schoen-Quigley', 'fraud_Kihn-Schuster',
       'fraud_Padberg-Rogahn', 'fraud_Lynch-Mohr', 'fraud_Hilpert-Conroy',
       'fraud_Jacobi Inc', 'fraud_Berge, Kautzer and Harris',
       'fraud_Hammes-Beatty', 'fraud_Gulgowski LLC',
       'fraud_Schuppe, Nolan and Hoeger', 'fraud_Pollich LLC',
       'fraud_Bernier and Sons', 'fraud_Wilkinson PLC',
       'fraud_Kling-Ernser', "fraud_O'Connell, Botsford and Hand",
       'fraud_Little-Gleichner', 'fraud_Champlin and Sons',
       'fraud_Hoppe-Parisian', 'fraud_Schuppe LLC', 'fraud_Emmerich-Rau',
       'fraud_Beier LLC', 'fraud_Champlin-Casper', 'fraud_Gerhold LLC',
       'fraud_Renner Ltd', 'fraud_Gaylord-Powlowski',
       'fraud_Prosacco, Kreiger and Kovacek', 'fraud_Eichmann-Kilback',
       "fraud_O'Hara-Wilderman", 'fraud_Terry Ltd',
       'fraud_Beier and Sons', "fraud_O'Keefe-Wisoky",
       'fraud_Simonis-Prohaska', 'fraud_Breitenberg-Hermiston',
       'fraud_Brown Inc', 'fraud_Fahey Inc',
       'fraud_Boehm, Block and Jakubowski',
       'fraud_Mante, Luettgen and Hackett', 'fraud_Thompson-Gleason',
       'fraud_Turcotte, Batz and Buckridge',
       'fraud_Goyette, Howell and Collier',
       'fraud_Jones, Sawayn and Romaguera', 'fraud_Medhurst Inc',
       'fraud_Bode-Schuster', 'fraud_Connelly-Carter',
       'fraud_Gottlieb-Hansen', 'fraud_Schroeder, Wolff and Hermiston',
       'fraud_Hettinger, McCullough and Fay',
       'fraud_Pouros, Walker and Spencer', 'fraud_Kub PLC',
       'fraud_Watsica LLC', 'fraud_Stiedemann Ltd',
       'fraud_Hauck, Dietrich and Funk', 'fraud_Labadie LLC',
       'fraud_Friesen Inc', 'fraud_Crist, Jakubowski and Littel',
       'fraud_Hodkiewicz, Prohaska and Paucek',
       'fraud_McDermott, Osinski and Morar', 'fraud_Fritsch and Sons',
       'fraud_Swaniawski, Nitzsche and Welch',
       'fraud_Windler, Goodwin and Kovacek',
       'fraud_Yost, Schamberger and Windler',
       'fraud_Metz, Russel and Metz', 'fraud_Erdman-Durgan',
       'fraud_Bahringer, Bergnaum and Quitzon', 'fraud_Veum-Koelpin',
       'fraud_Becker, Harris and Harvey', 'fraud_Monahan-Morar',
       'fraud_Johns Inc', 'fraud_Mosciski Group', 'fraud_Abbott-Steuber',
       'fraud_Schaefer Ltd', 'fraud_Dibbert-Green',
       'fraud_Weimann-Lockman', 'fraud_Kub-Heaney', 'fraud_Zulauf LLC',
       'fraud_Ratke and Sons', 'fraud_Jakubowski Inc', 'fraud_Beer-Jast',
       'fraud_Kautzer and Sons', 'fraud_Feil-Morar',
       'fraud_Johnston-Casper', 'fraud_Medhurst, Labadie and Gottlieb',
       "fraud_Lesch, D'Amore and Brown", 'fraud_Botsford PLC',
       'fraud_Bins-Howell', 'fraud_Kihn Inc',
       'fraud_Hartmann, Rowe and Hermann', 'fraud_Towne LLC',
       'fraud_Lynch-Wisozk', 'fraud_Kutch-Ferry', 'fraud_Goyette-Gerhold',
       'fraud_Bradtke, Torp and Bahringer', 'fraud_Homenick LLC',
       'fraud_Zemlak, Tillman and Cremin',
       'fraud_Schneider, Hayes and Nikolaus',
       'fraud_Schumm, McLaughlin and Carter', 'fraud_Nader-Maggio',
       'fraud_Haley, Batz and Auer', 'fraud_Yost-Rogahn',
       'fraud_Schoen, Nienow and Bauch',
       'fraud_Ledner, Hartmann and Feest', 'fraud_Collier LLC',
       'fraud_Schuppe-Schuppe', 'fraud_Walter, Hettinger and Kessler',
       'fraud_Bechtelar-Rippin', "fraud_Hamill-D'Amore",
       'fraud_Swift PLC', 'fraud_Cronin, Kshlerin and Weber',
       'fraud_Romaguera, Wehner and Tromp',
       'fraud_Feil, Hilpert and Koss', 'fraud_White and Sons',
       'fraud_Mueller, Gerhold and Mueller', 'fraud_Botsford and Sons',
       'fraud_Kirlin and Sons', 'fraud_Bednar PLC',
       'fraud_Runolfsdottir, Mueller and Hand', 'fraud_Kuphal-Toy',
       'fraud_Bahringer-Streich', 'fraud_Wuckert, Wintheiser and Friesen',
       'fraud_Crona and Sons', 'fraud_Prosacco LLC', 'fraud_Schiller Ltd',
       'fraud_Waelchi-Wolf', 'fraud_Torphy-Kertzmann',
       'fraud_McCullough, Hudson and Schuster', 'fraud_Baumbach Ltd',
       'fraud_Schiller, Blanda and Johnson', 'fraud_Cartwright PLC',
       'fraud_Reilly LLC', 'fraud_Cruickshank-Mills',
       'fraud_Altenwerth, Cartwright and Koss',
       'fraud_Effertz, Welch and Schowalter',
       'fraud_Klocko, Runolfsdottir and Breitenberg',
       'fraud_Ruecker-Mayert', 'fraud_Schroeder, Hauck and Treutel',
       'fraud_Lemke-Gutmann', 'fraud_Graham, Hegmann and Hammes',
       'fraud_Reilly and Sons', 'fraud_Stark-Koss', 'fraud_Daugherty LLC',
       'fraud_Denesik, Powlowski and Pouros', 'fraud_Rippin-VonRueden',
       'fraud_Heller PLC', 'fraud_Hills-Boyer', 'fraud_Cormier LLC',
       'fraud_Erdman-Ebert', 'fraud_Bogisich-Weimann',
       'fraud_Gutmann, McLaughlin and Wiza', 'fraud_Little Ltd',
       'fraud_Bode-Rempel', 'fraud_Kutch, Steuber and Gerhold',
       'fraud_Kessler Inc', 'fraud_Deckow-Dare', 'fraud_Rolfson-Kunde',
       'fraud_Marvin-Lind', 'fraud_Barrows PLC', 'fraud_Abbott-Rogahn',
       'fraud_Ziemann-Waters', 'fraud_Reinger, Weissnat and Strosin',
       'fraud_Heathcote, Yost and Kertzmann', 'fraud_Will Ltd',
       'fraud_Kutch-Wilderman', 'fraud_Hermiston, Russel and Price',
       'fraud_Schmidt-Larkin', 'fraud_Lang, Towne and Schuppe',
       'fraud_Weber, Thiel and Hammes',
       'fraud_Hahn, Bahringer and McLaughlin',
       'fraud_Koss, Hansen and Lueilwitz',
       'fraud_Roberts, Ryan and Smith', 'fraud_Hintz, Bauch and Smith',
       'fraud_Monahan, Hermann and Johns',
       'fraud_Bahringer, Osinski and Block',
       'fraud_Douglas, DuBuque and McKenzie', 'fraud_Hackett Group',
       'fraud_Schmeler-Howe', 'fraud_Predovic Inc', 'fraud_Langworth LLC',
       'fraud_Bartoletti and Sons', 'fraud_Bernhard-Lesch',
       'fraud_Satterfield-Lowe', 'fraud_Runte, Green and Emard',
       'fraud_Lowe, Dietrich and Erdman', 'fraud_Jast Ltd',
       'fraud_Welch, Rath and Koepp', 'fraud_Skiles LLC',
       'fraud_Ernser-Feest', 'fraud_Klein Group',
       'fraud_Torp, Muller and Borer', 'fraud_Kuhn Group',
       'fraud_Streich, Rolfson and Wilderman', 'fraud_Bins-Tillman',
       'fraud_Ankunding-Carroll', 'fraud_Hahn, Douglas and Schowalter',
       'fraud_Witting, Beer and Ernser', 'fraud_Morissette LLC',
       'fraud_Berge-Hills', 'fraud_Donnelly LLC', 'fraud_Zboncak LLC',
       'fraud_Turner, Ziemann and Lehner', 'fraud_Padberg-Sauer',
       'fraud_Schulist Ltd', 'fraud_Rau-Grant', 'fraud_Osinski Inc',
       'fraud_Berge-Ullrich', 'fraud_Wuckert-Goldner',
       'fraud_Kertzmann LLC', 'fraud_Daugherty, Pouros and Beahan',
       'fraud_Armstrong, Walter and Gottlieb', 'fraud_Conroy-Emard',
       'fraud_Moore, Williamson and Emmerich', 'fraud_Gleason and Sons',
       'fraud_Roberts, Daniel and Macejkovic', 'fraud_Turner LLC',
       'fraud_Crooks and Sons', 'fraud_Waelchi Inc',
       'fraud_Hoppe, Harris and Bednar', 'fraud_Effertz LLC',
       'fraud_Lubowitz-Walter', 'fraud_Hyatt-Blick', 'fraud_Carroll PLC',
       'fraud_Lemke and Sons', 'fraud_Treutel-King',
       'fraud_Fadel-Hilpert', 'fraud_Altenwerth-Kilback',
       'fraud_Bauch-Blanda', 'fraud_Sporer-Keebler', 'fraud_Hirthe-Beier',
       'fraud_Wisozk and Sons', 'fraud_Streich Ltd', 'fraud_Schoen Ltd',
       'fraud_Windler LLC', 'fraud_Nolan-Williamson',
       'fraud_Roob-Okuneva', 'fraud_Lakin, Ferry and Beatty',
       'fraud_Gottlieb Group', 'fraud_Harris Group', 'fraud_Fritsch LLC',
       'fraud_Corwin-Romaguera', 'fraud_Dietrich-Fadel',
       'fraud_Kling, Howe and Schneider', 'fraud_Kozey-Kuhlman',
       'fraud_Graham and Sons', 'fraud_Jacobi and Sons',
       'fraud_Eichmann, Hayes and Treutel',
       'fraud_Brown, Homenick and Lesch', 'fraud_Erdman-Schaden',
       'fraud_Durgan, Gislason and Spencer', 'fraud_Friesen-Ortiz',
       'fraud_Morissette-Schaefer', 'fraud_Nienow, Ankunding and Collier',
       'fraud_Cole, Hills and Jewess',
       'fraud_Conroy, Balistreri and Gorczany',
       'fraud_Reichel, Bradtke and Blanda',
       "fraud_O'Reilly, Mohr and Purdy", 'fraud_Ullrich Ltd',
       'fraud_Schroeder Group', 'fraud_Boyer-Haley',
       'fraud_Dare, Casper and Bartoletti',
       'fraud_Medhurst, Cartwright and Ebert', 'fraud_Quitzon-Goyette',
       'fraud_Wilkinson LLC', 'fraud_Romaguera and Sons',
       'fraud_Larkin Ltd', 'fraud_Fadel, Mertz and Rippin',
       'fraud_Huel Ltd', 'fraud_Cummerata-Hilpert', 'fraud_Zemlak Group',
       'fraud_Dare-Gibson', 'fraud_Adams-Barrows', 'fraud_Block-Hauck',
       'fraud_Howe PLC', 'fraud_Leffler-Goldner', 'fraud_Tillman LLC',
       'fraud_Pacocha-Weissnat', 'fraud_Morissette PLC',
       'fraud_Jerde-Hermann', 'fraud_Kihn, Brakus and Goyette',
       'fraud_Hills, Hegmann and Schaefer', 'fraud_Friesen Ltd',
       'fraud_Kilback and Sons', 'fraud_Ebert-Daugherty',
       'fraud_Hermiston, Pacocha and Smith', 'fraud_Auer LLC',
       'fraud_Fadel Inc', 'fraud_Daugherty-Thompson',
       'fraud_Romaguera Ltd', 'fraud_Parker-Kunde', 'fraud_Barton LLC',
       'fraud_Kassulke Inc', 'fraud_McLaughlin, Armstrong and Koepp',
       'fraud_Abernathy and Sons', 'fraud_Bahringer Group',
       'fraud_Connelly PLC', 'fraud_Willms, Kris and Bergnaum',
       'fraud_Thiel Ltd', 'fraud_Kris-Kertzmann',
       "fraud_O'Connell-Ullrich", 'fraud_Kozey-McDermott',

In [72]:
cardinality = pd.DataFrame({
    "Unique Values": df.nunique(),
    "Total Rows": len(df)
})

cardinality["Cardinality %"] = (
    cardinality["Unique Values"]
    / cardinality["Total Rows"]
    * 100
)

cardinality

                       Unique Values  Total Rows  Cardinality %
Unnamed: 0                   1296675     1296675     100.000000
trans_date_trans_time        1274791     1296675      98.312299
cc_num                           983     1296675       0.075809
merchant                         693     1296675       0.053444
category                          14     1296675       0.001080
amt                            52928     1296675       4.081825
first                            352     1296675       0.027146
last                             481     1296675       0.037095
gender                             2     1296675       0.000154
street                           983     1296675       0.075809
city                             894     1296675       0.068946
state                             51     1296675       0.003933
zip                              970     1296675       0.074807
lat                              968     1296675       0.074652
long                             969     1296675       0.074730
city_pop                         879     1296675       0.067789
job                              494     1296675       0.038097
dob                              968     1296675       0.074652
trans_num                    1296675     1296675     100.000000
unix_time                    1274823     1296675      98.314767
merch_lat                    1247805     1296675      96.231130
merch_long                   1275745     1296675      98.385872
is_fraud                           2     1296675       0.000154

In [82]:
df.memory_usage(deep=True).sum() / (1024 ** 2)

np.float64(897.7247018814087)

In [85]:
memory = pd.DataFrame({
    "dtype": df.dtypes,
    "Memory (MB)": (df.memory_usage(deep=True) / 1024**2).round(2),
    "Unique": df.nunique()
})

memory.sort_values("Memory (MB)", ascending=False)

                                dtype  Memory (MB)     Unique
trans_num              string[python]       100.17  1296675.0
merchant                       object        89.20      693.0
street                         object        88.08      983.0
job                            object        85.61      494.0
category                       object        73.61       14.0
city                           object        71.29      894.0
last                           object        68.15      481.0
first                          object        68.11      352.0
state                          object        63.07       51.0
gender                         object        61.83        2.0
merch_lat                     float64         9.89  1247805.0
dob                    datetime64[ns]         9.89      968.0
Unnamed: 0                      int64         9.89  1296675.0
amt                           float64         9.89    52928.0
cc_num                          int64         9.89      983.0
city_pop                        int64         9.89      879.0
merch_long                    float64         9.89  1275745.0
long                          float64         9.89      969.0
lat                           float64         9.89      968.0
is_fraud                        int64         9.89        2.0
unix_time                       int64         9.89  1274823.0
trans_date_trans_time  datetime64[ns]         9.89  1274791.0
zip                             int64         9.89      970.0
Index                             NaN         0.00        NaN

In [1]:
df.unix_times.max()

NameError: name 'df' is not defined